apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-kuhcmphx
  janus-idp.io/tekton: go-kuhcmphx
  backstage.io/kubernetes-id: go-kuhcmphx
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-kuhcmphx
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
